#!/usr/bin/env python3
"""Build a one-page printable reference sheet for a TI-84 Evo Python program.

Renders assets/handout_template.html with the program's details, then converts
it to PDF with headless Chrome or Edge. If neither browser is found the HTML is
kept and you print it to PDF from the browser -- the handout is still delivered.

Usage:
    python make_handout.py --spec handout.json --out TIPCALC-handout.pdf
    python make_handout.py --spec handout.json --out out.pdf --html-only

handout.json:
    {
      "program":  "TIPCALC",
      "title":    "Tip and total",
      "purpose":  "One sentence on what it does and who it is for.",
      "source":   "TIPCALC.py",
      "formula":  "tip = bill * pct / 100\\ntotal = bill + tip",
      "prompts":  ["Bill amount: the pre-tip total, e.g. 48.50"],
      "outputs":  ["Tip: the tip in currency, 2 decimals"],
      "test_case": "Bill amount: [48.50]\\nTip percent: [18]\\nTip:   8.73",
      "quirks":   ["Any prompt accepts an expression, e.g. 40+8.50."],
      "mode_note": "Mode does not matter - arithmetic only.",
      "upload_steps": ["optional; sensible defaults are used if omitted"],
      "footer": "optional footer line"
    }

Square brackets in "test_case" mark what the student types; they are rendered
highlighted and the brackets are stripped.

Exit codes: 0 ok (PDF or HTML written), 1 failure, 2 bad invocation.
"""

import argparse
import datetime
import html
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATE = os.path.join(HERE, os.pardir, "assets", "handout_template.html")

DEFAULT_UPLOAD_STEPS = [
    "Open <b>connectevo.ti.com</b> in Chrome (v143+) and accept the terms.",
    "Plug the calculator in with a USB-C <i>data</i> cable and switch it on.",
    "Click <b>CONNECT TO CALCULATOR</b>, pick your calculator, click <b>Connect</b>.",
    "Click <b>SEND TO CALCULATOR</b> and choose <code>{{PROGRAM}}.py</code>.",
    "Check the name reads <code>{{PROGRAM}}</code>, not <code>PYTHON01</code>. Send.",
]

CHROME_CANDIDATES = [
    "chrome", "google-chrome", "google-chrome-stable", "chromium",
    "chromium-browser", "msedge",
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    os.path.expandvars(r"%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe"),
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
]


def find_browser():
    for cand in CHROME_CANDIDATES:
        if os.path.sep in cand or (os.altsep and os.altsep in cand):
            if os.path.isfile(cand):
                return cand
        else:
            found = shutil.which(cand)
            if found:
                return found
    return None


def li(items):
    return "\n".join("<li>%s</li>" % html.escape(str(x), quote=False)
                     for x in items) or "<li>&mdash;</li>"


def li_raw(items):
    """List items that may contain intentional HTML (upload steps)."""
    return "\n".join("<li>%s</li>" % x for x in items) or "<li>&mdash;</li>"


def render_testcase(text):
    """Escape, then highlight [typed input] as <span class="u">."""
    escaped = html.escape(text, quote=False)
    return re.sub(r"\[([^\]]*)\]", r'<span class="u">\1</span>', escaped)


def build_html(spec, source_code):
    with open(TEMPLATE, "r", encoding="utf-8") as fh:
        tpl = fh.read()

    program = str(spec.get("program", "PROGRAM")).upper()
    steps = spec.get("upload_steps") or DEFAULT_UPLOAD_STEPS
    steps = [s.replace("{{PROGRAM}}", program) for s in steps]

    values = {
        "PROGRAM": html.escape(program, quote=False),
        "TITLE": html.escape(str(spec.get("title", "")), quote=False),
        "PURPOSE": html.escape(str(spec.get("purpose", "")), quote=False),
        "DATE": datetime.date.today().isoformat(),
        "PROMPTS": li(spec.get("prompts", [])),
        "OUTPUTS": li(spec.get("outputs", [])),
        "FORMULA": html.escape(str(spec.get("formula", "")), quote=False),
        "UPLOAD_STEPS": li_raw(steps),
        "TESTCASE": render_testcase(str(spec.get("test_case", ""))),
        "QUIRKS": li(spec.get("quirks", [])),
        "MODE_NOTE": html.escape(str(spec.get("mode_note", "")), quote=False),
        "SOURCE": html.escape(source_code, quote=False),
        "FOOTER": html.escape(
            str(spec.get("footer", "Generated by ti84-evo-scripter")),
            quote=False),
    }
    for key, val in values.items():
        tpl = tpl.replace("{{%s}}" % key, val)
    return tpl


def to_pdf(html_path, pdf_path, browser):
    profile = tempfile.mkdtemp(prefix="ti84handout-")
    url = "file:///" + os.path.abspath(html_path).replace(os.sep, "/")
    cmd = [
        browser,
        "--headless=new",
        "--disable-gpu",
        "--no-sandbox",
        "--no-first-run",
        "--no-pdf-header-footer",
        "--user-data-dir=" + profile,
        "--print-to-pdf=" + os.path.abspath(pdf_path),
        url,
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=90)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    finally:
        shutil.rmtree(profile, ignore_errors=True)

    if os.path.isfile(pdf_path) and os.path.getsize(pdf_path) > 0:
        return True, ""
    detail = (proc.stderr or proc.stdout or "").strip().splitlines()
    return False, (detail[-1] if detail else "browser produced no PDF")


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spec", required=True, help="handout JSON spec")
    ap.add_argument("--out", required=True, help="output .pdf path")
    ap.add_argument("--html-only", action="store_true",
                    help="write the HTML and skip PDF conversion")
    args = ap.parse_args(argv)

    if not os.path.isfile(args.spec):
        print("error: no such spec: %s" % args.spec, file=sys.stderr)
        return 2

    with open(args.spec, "r", encoding="utf-8") as fh:
        spec = json.load(fh)

    src_path = spec.get("source")
    if src_path and not os.path.isabs(src_path):
        src_path = os.path.join(os.path.dirname(os.path.abspath(args.spec)),
                                src_path)
    if not src_path or not os.path.isfile(src_path):
        print("error: spec 'source' must point at the program .py file "
              "(got %r)" % spec.get("source"), file=sys.stderr)
        return 2

    with open(src_path, "r", encoding="utf-8") as fh:
        source_code = fh.read()

    out_pdf = os.path.abspath(args.out)
    out_dir = os.path.dirname(out_pdf)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    out_html = os.path.splitext(out_pdf)[0] + ".html"

    with open(out_html, "w", encoding="utf-8") as fh:
        fh.write(build_html(spec, source_code))
    print("HTML written: %s" % out_html)

    if args.html_only:
        print("PDF skipped (--html-only). Open the HTML and print to PDF.")
        return 0

    browser = find_browser()
    if not browser:
        print("PDF skipped: no Chrome or Edge found on PATH or in the usual "
              "install locations.")
        print("  -> Open the HTML above in a browser and use Ctrl+P > "
              "Save as PDF (A4, margins Default, Background graphics ON).")
        return 0

    ok, err = to_pdf(out_html, out_pdf, browser)
    if ok:
        size = os.path.getsize(out_pdf)
        print("PDF written:  %s  (%d bytes, via %s)"
              % (out_pdf, size, os.path.basename(browser)))
        return 0

    print("PDF conversion failed via %s: %s" % (browser, err))
    print("  -> The HTML is complete. Open it and print to PDF manually.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
